"""
Auto-generated designer template base class
This file is auto-generated by Anvil - typically you wouldn't edit it directly
"""
from anvil import *


class MainFormTemplate(ColumnPanelTemplate):
    def __init__(self, **properties):
        self.init_components(**properties)
